// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: GSPv45

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_screenMain
void ui_screenMain_screen_init(void);
void ui_event_screenMain( lv_event_t * e);
lv_obj_t *ui_screenMain;
lv_obj_t *ui_LabelLat;
lv_obj_t *ui_LabelLon;
lv_obj_t *ui_LabelSats;
lv_obj_t *ui_LabelDHOP;
lv_obj_t *ui_LatData;
lv_obj_t *ui_LonData;
lv_obj_t *ui_TimeData;
lv_obj_t *ui_DateData;
lv_obj_t *ui_HDOPData;
void ui_event_SliderBrightness( lv_event_t * e);
lv_obj_t *ui_SliderBrightness;
lv_obj_t *ui_ImgCompass;
lv_obj_t *ui_MikeJoe;
lv_obj_t *ui_AltData;
lv_obj_t *ui_labelAlt;
lv_obj_t *ui_LabelSpeed;
lv_obj_t *ui_SpeedData;
lv_obj_t *ui_labelDist;
lv_obj_t *ui_DistData;
lv_obj_t *ui_SatData;
lv_obj_t *ui_HeadingData;
void ui_event_BtnAlt( lv_event_t * e);
lv_obj_t *ui_BtnAlt;
void ui_event_BtnSpeed( lv_event_t * e);
lv_obj_t *ui_BtnSpeed;
void ui_event_BtnDist( lv_event_t * e);
lv_obj_t *ui_BtnDist;
void ui_event_BtnDate( lv_event_t * e);
lv_obj_t *ui_BtnDate;
void ui_event_BtnTime( lv_event_t * e);
lv_obj_t *ui_BtnTime;
void ui_event_BtnLat( lv_event_t * e);
lv_obj_t *ui_BtnLat;
void ui_event_BtnLon( lv_event_t * e);
lv_obj_t *ui_BtnLon;
lv_obj_t *ui_Volts;
lv_obj_t *ui_LabelVolts;
void ui_event_LabelBatteryLevel( lv_event_t * e);
lv_obj_t *ui_LabelBatteryLevel;
lv_obj_t *ui_Flash;
lv_obj_t *ui_lblDate;
lv_obj_t *ui_Label6;


// SCREEN: ui_screenSats
void ui_screenSats_screen_init(void);
void ui_event_screenSats( lv_event_t * e);
lv_obj_t *ui_screenSats;
lv_obj_t *ui_SatsCircle;
lv_obj_t *ui_Sat00;
lv_obj_t *ui_Sat01;
lv_obj_t *ui_Sat02;
lv_obj_t *ui_Sat03;
lv_obj_t *ui_Sat04;
lv_obj_t *ui_Sat05;
lv_obj_t *ui_Sat06;
lv_obj_t *ui_Sat07;
lv_obj_t *ui_Sat08;
lv_obj_t *ui_Sat09;
lv_obj_t *ui_Sat10;
lv_obj_t *ui_Sat11;
lv_obj_t *ui_Sat12;
lv_obj_t *ui_Sat13;
lv_obj_t *ui_Sat14;
lv_obj_t *ui_Sat15;
lv_obj_t *ui_Sat16;
lv_obj_t *ui_Sat17;
lv_obj_t *ui_Sat18;
lv_obj_t *ui_Sat19;
lv_obj_t *ui_Sat20;
lv_obj_t *ui_Sat21;
lv_obj_t *ui_Sat22;
lv_obj_t *ui_Sat23;
lv_obj_t *ui_Sat24;
lv_obj_t *ui_Sat25;
lv_obj_t *ui_Sat26;
lv_obj_t *ui_Sat27;
lv_obj_t *ui_Sat28;
lv_obj_t *ui_Sat29;
lv_obj_t *ui_Sat30;
lv_obj_t *ui_Sat31;
lv_obj_t *ui_Sat32;


// SCREEN: ui_screenInfo
void ui_screenInfo_screen_init(void);
void ui_event_screenInfo( lv_event_t * e);
lv_obj_t *ui_screenInfo;
lv_obj_t *ui_CharProcessed;
lv_obj_t *ui_SentenceFixed;
lv_obj_t *ui_FailCheckSum;
lv_obj_t *ui_PassedCheckSum;
lv_obj_t *ui_CharData;
lv_obj_t *ui_SentFixedData;
lv_obj_t *ui_FailedCheckSumData;
lv_obj_t *ui_PassCheckSumData;
lv_obj_t *ui_LatAvg;
lv_obj_t *ui_LonAvg;
lv_obj_t *ui_SunRise;
lv_obj_t *ui_SunSet;
lv_obj_t *ui_MoonRise;
lv_obj_t *ui_MoonSet;
lv_obj_t *ui_LatAvgData;
lv_obj_t *ui_LonAvgData;
lv_obj_t *ui_SunRiseData;
lv_obj_t *ui_SunSetData;
lv_obj_t *ui_MoonRiseData;
lv_obj_t *ui_MoonSetData;
void ui_event_CountData( lv_event_t * e);
lv_obj_t *ui_CountData;
lv_obj_t *ui_Count;
lv_obj_t *ui_M000;
lv_obj_t *ui_M030;
lv_obj_t *ui_M060;
lv_obj_t *ui_M090;
lv_obj_t *ui_M120;
lv_obj_t *ui_M150;
lv_obj_t *ui_M180;
lv_obj_t *ui_M210;
lv_obj_t *ui_M240;
lv_obj_t *ui_M270;
lv_obj_t *ui_M300;
lv_obj_t *ui_M330;
lv_obj_t *ui_MoonPhases;
lv_obj_t *ui____initial_actions0;
const lv_img_dsc_t *ui_imgset_m[13] = {&ui_img_m000_png, &ui_img_m030_png, &ui_img_m060_png, &ui_img_m090_png, &ui_img_m120_png, &ui_img_m150_png, &ui_img_m180_png, &ui_img_m210_png, &ui_img_m240_png, &ui_img_m270_png, &ui_img_m300_png, &ui_img_m330_png, &ui_img_m336_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_screenMain( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT  ) {
lv_indev_wait_release(lv_indev_get_act());
      _ui_screen_change( &ui_screenSats, LV_SCR_LOAD_ANIM_NONE, 200, 0, &ui_screenSats_screen_init);
}
}
void ui_event_SliderBrightness( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_VALUE_CHANGED) {
      Brightness( e );
}
}
void ui_event_BtnAlt( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_LONG_PRESSED) {
      BtnAlt( e );
}
}
void ui_event_BtnSpeed( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_LONG_PRESSED) {
      BtnSpeed( e );
}
}
void ui_event_BtnDist( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_LONG_PRESSED) {
      BtnDist( e );
}
if ( event_code == LV_EVENT_LONG_PRESSED) {
      BtnDist_Reset( e );
}
}
void ui_event_BtnDate( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_LONG_PRESSED) {
      BtnDate( e );
}
}
void ui_event_BtnTime( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_RELEASED) {
      BtnTime( e );
}
}
void ui_event_BtnLat( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_LONG_PRESSED) {
      BtnLat( e );
}
}
void ui_event_BtnLon( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_LONG_PRESSED) {
      BtnLon( e );
}
}
void ui_event_LabelBatteryLevel( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_VALUE_CHANGED) {
      BatteryLevel( e );
}
}
void ui_event_screenSats( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT  ) {
lv_indev_wait_release(lv_indev_get_act());
      _ui_screen_change( &ui_screenInfo, LV_SCR_LOAD_ANIM_NONE, 200, 0, &ui_screenInfo_screen_init);
}
if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT  ) {
lv_indev_wait_release(lv_indev_get_act());
      _ui_screen_change( &ui_screenMain, LV_SCR_LOAD_ANIM_NONE, 200, 0, &ui_screenMain_screen_init);
}
}
void ui_event_screenInfo( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT  ) {
lv_indev_wait_release(lv_indev_get_act());
      _ui_screen_change( &ui_screenSats, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_screenSats_screen_init);
}
}
void ui_event_CountData( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_LONG_PRESSED) {
      ( e );
}
}

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), true, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_screenMain_screen_init();
ui_screenSats_screen_init();
ui_screenInfo_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_screenMain);
}
