// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: GSPv45

#ifndef _GSPV45_UI_H
#define _GSPV45_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_screenMain
void ui_screenMain_screen_init(void);
void ui_event_screenMain( lv_event_t * e);
extern lv_obj_t *ui_screenMain;
extern lv_obj_t *ui_LabelLat;
extern lv_obj_t *ui_LabelLon;
extern lv_obj_t *ui_LabelSats;
extern lv_obj_t *ui_LabelDHOP;
extern lv_obj_t *ui_LatData;
extern lv_obj_t *ui_LonData;
extern lv_obj_t *ui_TimeData;
extern lv_obj_t *ui_DateData;
extern lv_obj_t *ui_HDOPData;
void ui_event_SliderBrightness( lv_event_t * e);
extern lv_obj_t *ui_SliderBrightness;
extern lv_obj_t *ui_ImgCompass;
extern lv_obj_t *ui_MikeJoe;
extern lv_obj_t *ui_AltData;
extern lv_obj_t *ui_labelAlt;
extern lv_obj_t *ui_LabelSpeed;
extern lv_obj_t *ui_SpeedData;
extern lv_obj_t *ui_labelDist;
extern lv_obj_t *ui_DistData;
extern lv_obj_t *ui_SatData;
extern lv_obj_t *ui_HeadingData;
void ui_event_BtnAlt( lv_event_t * e);
extern lv_obj_t *ui_BtnAlt;
void ui_event_BtnSpeed( lv_event_t * e);
extern lv_obj_t *ui_BtnSpeed;
void ui_event_BtnDist( lv_event_t * e);
extern lv_obj_t *ui_BtnDist;
void ui_event_BtnDate( lv_event_t * e);
extern lv_obj_t *ui_BtnDate;
void ui_event_BtnTime( lv_event_t * e);
extern lv_obj_t *ui_BtnTime;
void ui_event_BtnLat( lv_event_t * e);
extern lv_obj_t *ui_BtnLat;
void ui_event_BtnLon( lv_event_t * e);
extern lv_obj_t *ui_BtnLon;
extern lv_obj_t *ui_Volts;
extern lv_obj_t *ui_LabelVolts;
void ui_event_LabelBatteryLevel( lv_event_t * e);
extern lv_obj_t *ui_LabelBatteryLevel;
extern lv_obj_t *ui_Flash;
extern lv_obj_t *ui_lblDate;
extern lv_obj_t *ui_Label6;
// SCREEN: ui_screenSats
void ui_screenSats_screen_init(void);
void ui_event_screenSats( lv_event_t * e);
extern lv_obj_t *ui_screenSats;
extern lv_obj_t *ui_SatsCircle;
extern lv_obj_t *ui_Sat00;
extern lv_obj_t *ui_Sat01;
extern lv_obj_t *ui_Sat02;
extern lv_obj_t *ui_Sat03;
extern lv_obj_t *ui_Sat04;
extern lv_obj_t *ui_Sat05;
extern lv_obj_t *ui_Sat06;
extern lv_obj_t *ui_Sat07;
extern lv_obj_t *ui_Sat08;
extern lv_obj_t *ui_Sat09;
extern lv_obj_t *ui_Sat10;
extern lv_obj_t *ui_Sat11;
extern lv_obj_t *ui_Sat12;
extern lv_obj_t *ui_Sat13;
extern lv_obj_t *ui_Sat14;
extern lv_obj_t *ui_Sat15;
extern lv_obj_t *ui_Sat16;
extern lv_obj_t *ui_Sat17;
extern lv_obj_t *ui_Sat18;
extern lv_obj_t *ui_Sat19;
extern lv_obj_t *ui_Sat20;
extern lv_obj_t *ui_Sat21;
extern lv_obj_t *ui_Sat22;
extern lv_obj_t *ui_Sat23;
extern lv_obj_t *ui_Sat24;
extern lv_obj_t *ui_Sat25;
extern lv_obj_t *ui_Sat26;
extern lv_obj_t *ui_Sat27;
extern lv_obj_t *ui_Sat28;
extern lv_obj_t *ui_Sat29;
extern lv_obj_t *ui_Sat30;
extern lv_obj_t *ui_Sat31;
extern lv_obj_t *ui_Sat32;
// SCREEN: ui_screenInfo
void ui_screenInfo_screen_init(void);
void ui_event_screenInfo( lv_event_t * e);
extern lv_obj_t *ui_screenInfo;
extern lv_obj_t *ui_CharProcessed;
extern lv_obj_t *ui_SentenceFixed;
extern lv_obj_t *ui_FailCheckSum;
extern lv_obj_t *ui_PassedCheckSum;
extern lv_obj_t *ui_CharData;
extern lv_obj_t *ui_SentFixedData;
extern lv_obj_t *ui_FailedCheckSumData;
extern lv_obj_t *ui_PassCheckSumData;
extern lv_obj_t *ui_LatAvg;
extern lv_obj_t *ui_LonAvg;
extern lv_obj_t *ui_SunRise;
extern lv_obj_t *ui_SunSet;
extern lv_obj_t *ui_MoonRise;
extern lv_obj_t *ui_MoonSet;
extern lv_obj_t *ui_LatAvgData;
extern lv_obj_t *ui_LonAvgData;
extern lv_obj_t *ui_SunRiseData;
extern lv_obj_t *ui_SunSetData;
extern lv_obj_t *ui_MoonRiseData;
extern lv_obj_t *ui_MoonSetData;
void ui_event_CountData( lv_event_t * e);
extern lv_obj_t *ui_CountData;
extern lv_obj_t *ui_Count;
extern lv_obj_t *ui_M000;
extern lv_obj_t *ui_M030;
extern lv_obj_t *ui_M060;
extern lv_obj_t *ui_M090;
extern lv_obj_t *ui_M120;
extern lv_obj_t *ui_M150;
extern lv_obj_t *ui_M180;
extern lv_obj_t *ui_M210;
extern lv_obj_t *ui_M240;
extern lv_obj_t *ui_M270;
extern lv_obj_t *ui_M300;
extern lv_obj_t *ui_M330;
extern lv_obj_t *ui_MoonPhases;
extern lv_obj_t *ui____initial_actions0;

LV_IMG_DECLARE( ui_img_compass_circle_png);   // assets/Compass_circle.png
LV_IMG_DECLARE( ui_img_flash_png);   // assets/flash.png
LV_IMG_DECLARE( ui_img_satview_png);   // assets/SatView.png
LV_IMG_DECLARE( ui_img_m000_png);   // assets/m000.png
LV_IMG_DECLARE( ui_img_m030_png);   // assets/m030.png
LV_IMG_DECLARE( ui_img_m060_png);   // assets/m060.png
LV_IMG_DECLARE( ui_img_m090_png);   // assets/m090.png
LV_IMG_DECLARE( ui_img_m120_png);   // assets/m120.png
LV_IMG_DECLARE( ui_img_m150_png);   // assets/m150.png
LV_IMG_DECLARE( ui_img_m180_png);   // assets/m180.png
LV_IMG_DECLARE( ui_img_m210_png);   // assets/m210.png
LV_IMG_DECLARE( ui_img_m240_png);   // assets/m240.png
LV_IMG_DECLARE( ui_img_m270_png);   // assets/m270.png
LV_IMG_DECLARE( ui_img_m300_png);   // assets/m300.png
LV_IMG_DECLARE( ui_img_m330_png);   // assets/m330.png
LV_IMG_DECLARE( ui_img_m336_png);   // assets/m336.png


LV_FONT_DECLARE( ui_font_Roboto26);
LV_FONT_DECLARE( ui_font_Roboto28);
LV_FONT_DECLARE( ui_font_RobotoBold26);
LV_FONT_DECLARE( ui_font_RobotoBold30);
LV_FONT_DECLARE( ui_font_RobotoBold32);


void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
