// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: GSPv45

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void Brightness(lv_event_t * e);
void BtnAlt(lv_event_t * e);
void BtnSpeed(lv_event_t * e);
void BtnDist(lv_event_t * e);
void BtnDist_Reset(lv_event_t * e);
void BtnDate(lv_event_t * e);
void BtnTime(lv_event_t * e);
void BtnLat(lv_event_t * e);
void BtnLon(lv_event_t * e);
void BatteryLevel(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
