// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: GSP_2.18

#include "ui.h"

void Brightness(lv_event_t * e)
{
	// Your code here
}

void BatteryLevel(lv_event_t * e)
{
	// Your code here
}
