// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: GSPv45

#include "ui.h"

void ui_screenInfo_screen_init(void)
{
ui_screenInfo = lv_obj_create(NULL);
lv_obj_clear_flag( ui_screenInfo, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_screenInfo, lv_color_hex(0x080000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_screenInfo, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_CharProcessed = lv_label_create(ui_screenInfo);
lv_obj_set_width( ui_CharProcessed, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_CharProcessed, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_CharProcessed, -211 );
lv_obj_set_y( ui_CharProcessed, 29 );
lv_obj_set_align( ui_CharProcessed, LV_ALIGN_CENTER );
lv_label_set_text(ui_CharProcessed,"CharProcessed");
lv_obj_set_style_text_color(ui_CharProcessed, lv_color_hex(0xD1E1E1), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_CharProcessed, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_CharProcessed, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SentenceFixed = lv_label_create(ui_screenInfo);
lv_obj_set_width( ui_SentenceFixed, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SentenceFixed, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_SentenceFixed, 212 );
lv_obj_set_y( ui_SentenceFixed, 29 );
lv_obj_set_align( ui_SentenceFixed, LV_ALIGN_CENTER );
lv_label_set_text(ui_SentenceFixed,"SentenceFixed");
lv_obj_set_style_text_color(ui_SentenceFixed, lv_color_hex(0xD1E1E1), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_SentenceFixed, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_SentenceFixed, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_FailCheckSum = lv_label_create(ui_screenInfo);
lv_obj_set_width( ui_FailCheckSum, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_FailCheckSum, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_FailCheckSum, -214 );
lv_obj_set_y( ui_FailCheckSum, 109 );
lv_obj_set_align( ui_FailCheckSum, LV_ALIGN_CENTER );
lv_label_set_text(ui_FailCheckSum,"Fail Checksum");
lv_obj_set_style_text_color(ui_FailCheckSum, lv_color_hex(0xD1E1E1), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_FailCheckSum, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_FailCheckSum, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PassedCheckSum = lv_label_create(ui_screenInfo);
lv_obj_set_width( ui_PassedCheckSum, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_PassedCheckSum, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_PassedCheckSum, 212 );
lv_obj_set_y( ui_PassedCheckSum, 109 );
lv_obj_set_align( ui_PassedCheckSum, LV_ALIGN_CENTER );
lv_label_set_text(ui_PassedCheckSum,"PassCheckSum");
lv_obj_set_style_text_color(ui_PassedCheckSum, lv_color_hex(0xD1E1E1), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_PassedCheckSum, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_PassedCheckSum, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_CharData = lv_label_create(ui_screenInfo);
lv_obj_set_width( ui_CharData, 157);
lv_obj_set_height( ui_CharData, 44);
lv_obj_set_x( ui_CharData, -214 );
lv_obj_set_y( ui_CharData, 63 );
lv_obj_set_align( ui_CharData, LV_ALIGN_CENTER );
lv_label_set_text(ui_CharData,"888888888");
lv_obj_set_style_text_color(ui_CharData, lv_color_hex(0x7BFB0A), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_CharData, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_CharData, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_CharData, &ui_font_Roboto26, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_CharData, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_CharData, lv_color_hex(0x050000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_CharData, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_CharData, lv_color_hex(0xF90505), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_CharData, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_CharData, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_CharData, 6, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_CharData, 6, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_CharData, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_CharData, 6, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SentFixedData = lv_label_create(ui_screenInfo);
lv_obj_set_width( ui_SentFixedData, 157);
lv_obj_set_height( ui_SentFixedData, 44);
lv_obj_set_x( ui_SentFixedData, 214 );
lv_obj_set_y( ui_SentFixedData, 63 );
lv_obj_set_align( ui_SentFixedData, LV_ALIGN_CENTER );
lv_label_set_text(ui_SentFixedData,"888888888");
lv_obj_set_style_text_color(ui_SentFixedData, lv_color_hex(0x7BFB0A), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_SentFixedData, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_SentFixedData, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_SentFixedData, &ui_font_Roboto26, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_SentFixedData, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_SentFixedData, lv_color_hex(0x050000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SentFixedData, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_SentFixedData, lv_color_hex(0xF90505), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_SentFixedData, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_SentFixedData, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_SentFixedData, 6, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_SentFixedData, 6, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_SentFixedData, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_SentFixedData, 6, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_FailedCheckSumData = lv_label_create(ui_screenInfo);
lv_obj_set_width( ui_FailedCheckSumData, 157);
lv_obj_set_height( ui_FailedCheckSumData, 44);
lv_obj_set_x( ui_FailedCheckSumData, -214 );
lv_obj_set_y( ui_FailedCheckSumData, 143 );
lv_obj_set_align( ui_FailedCheckSumData, LV_ALIGN_CENTER );
lv_label_set_text(ui_FailedCheckSumData,"888888888");
lv_obj_set_style_text_color(ui_FailedCheckSumData, lv_color_hex(0x7BFB0A), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_FailedCheckSumData, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_FailedCheckSumData, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_FailedCheckSumData, &ui_font_Roboto26, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_FailedCheckSumData, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_FailedCheckSumData, lv_color_hex(0x050000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_FailedCheckSumData, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_FailedCheckSumData, lv_color_hex(0xF90505), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_FailedCheckSumData, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_FailedCheckSumData, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_FailedCheckSumData, 6, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_FailedCheckSumData, 6, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_FailedCheckSumData, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_FailedCheckSumData, 6, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PassCheckSumData = lv_label_create(ui_screenInfo);
lv_obj_set_width( ui_PassCheckSumData, 157);
lv_obj_set_height( ui_PassCheckSumData, 44);
lv_obj_set_x( ui_PassCheckSumData, 214 );
lv_obj_set_y( ui_PassCheckSumData, 143 );
lv_obj_set_align( ui_PassCheckSumData, LV_ALIGN_CENTER );
lv_label_set_text(ui_PassCheckSumData,"888888888");
lv_obj_set_style_text_color(ui_PassCheckSumData, lv_color_hex(0x7BFB0A), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_PassCheckSumData, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_PassCheckSumData, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_PassCheckSumData, &ui_font_Roboto26, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_PassCheckSumData, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_PassCheckSumData, lv_color_hex(0x050000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_PassCheckSumData, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_PassCheckSumData, lv_color_hex(0xF90505), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_PassCheckSumData, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_PassCheckSumData, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_PassCheckSumData, 6, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_PassCheckSumData, 6, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_PassCheckSumData, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_PassCheckSumData, 6, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LatAvg = lv_label_create(ui_screenInfo);
lv_obj_set_width( ui_LatAvg, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LatAvg, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LatAvg, -222 );
lv_obj_set_y( ui_LatAvg, -211 );
lv_obj_set_align( ui_LatAvg, LV_ALIGN_CENTER );
lv_label_set_text(ui_LatAvg,"Latitude Avg");
lv_obj_set_style_text_color(ui_LatAvg, lv_color_hex(0xD1E1E1), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LatAvg, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LatAvg, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LonAvg = lv_label_create(ui_screenInfo);
lv_obj_set_width( ui_LonAvg, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LonAvg, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LonAvg, 212 );
lv_obj_set_y( ui_LonAvg, -211 );
lv_obj_set_align( ui_LonAvg, LV_ALIGN_CENTER );
lv_label_set_text(ui_LonAvg,"Longitude Avg");
lv_obj_set_style_text_color(ui_LonAvg, lv_color_hex(0xD1E1E1), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LonAvg, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LonAvg, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SunRise = lv_label_create(ui_screenInfo);
lv_obj_set_width( ui_SunRise, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SunRise, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_SunRise, -240 );
lv_obj_set_y( ui_SunRise, -138 );
lv_obj_set_align( ui_SunRise, LV_ALIGN_CENTER );
lv_label_set_text(ui_SunRise,"Sun Rise");
lv_obj_set_style_text_color(ui_SunRise, lv_color_hex(0xD1E1E1), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_SunRise, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_SunRise, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SunSet = lv_label_create(ui_screenInfo);
lv_obj_set_width( ui_SunSet, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SunSet, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_SunSet, 240 );
lv_obj_set_y( ui_SunSet, -138 );
lv_obj_set_align( ui_SunSet, LV_ALIGN_CENTER );
lv_label_set_text(ui_SunSet,"Sun Set");
lv_obj_set_style_text_color(ui_SunSet, lv_color_hex(0xD1E1E1), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_SunSet, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_SunSet, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_MoonRise = lv_label_create(ui_screenInfo);
lv_obj_set_width( ui_MoonRise, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_MoonRise, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_MoonRise, -229 );
lv_obj_set_y( ui_MoonRise, -58 );
lv_obj_set_align( ui_MoonRise, LV_ALIGN_CENTER );
lv_label_set_text(ui_MoonRise,"Moon Rise");
lv_obj_set_style_text_color(ui_MoonRise, lv_color_hex(0xD1E1E1), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_MoonRise, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_MoonRise, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_MoonSet = lv_label_create(ui_screenInfo);
lv_obj_set_width( ui_MoonSet, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_MoonSet, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_MoonSet, 234 );
lv_obj_set_y( ui_MoonSet, -58 );
lv_obj_set_align( ui_MoonSet, LV_ALIGN_CENTER );
lv_label_set_text(ui_MoonSet,"Moon Set");
lv_obj_set_style_text_color(ui_MoonSet, lv_color_hex(0xD1E1E1), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_MoonSet, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_MoonSet, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LatAvgData = lv_label_create(ui_screenInfo);
lv_obj_set_width( ui_LatAvgData, 200);
lv_obj_set_height( ui_LatAvgData, 44);
lv_obj_set_x( ui_LatAvgData, -196 );
lv_obj_set_y( ui_LatAvgData, -177 );
lv_obj_set_align( ui_LatAvgData, LV_ALIGN_CENTER );
lv_label_set_text(ui_LatAvgData,"888888888888");
lv_obj_set_style_text_color(ui_LatAvgData, lv_color_hex(0x7BFB0A), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LatAvgData, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_LatAvgData, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LatAvgData, &ui_font_Roboto26, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_LatAvgData, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_LatAvgData, lv_color_hex(0x050000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_LatAvgData, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_LatAvgData, lv_color_hex(0xF90505), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_LatAvgData, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_LatAvgData, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_LatAvgData, 6, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_LatAvgData, 6, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_LatAvgData, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_LatAvgData, 6, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LonAvgData = lv_label_create(ui_screenInfo);
lv_obj_set_width( ui_LonAvgData, 200);
lv_obj_set_height( ui_LonAvgData, 44);
lv_obj_set_x( ui_LonAvgData, 196 );
lv_obj_set_y( ui_LonAvgData, -177 );
lv_obj_set_align( ui_LonAvgData, LV_ALIGN_CENTER );
lv_label_set_text(ui_LonAvgData,"888888888888");
lv_obj_set_style_text_color(ui_LonAvgData, lv_color_hex(0x7BFB0A), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LonAvgData, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_LonAvgData, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LonAvgData, &ui_font_Roboto26, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_LonAvgData, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_LonAvgData, lv_color_hex(0x050000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_LonAvgData, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_LonAvgData, lv_color_hex(0xF90505), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_LonAvgData, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_LonAvgData, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_LonAvgData, 6, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_LonAvgData, 6, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_LonAvgData, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_LonAvgData, 6, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SunRiseData = lv_label_create(ui_screenInfo);
lv_obj_set_width( ui_SunRiseData, 125);
lv_obj_set_height( ui_SunRiseData, 44);
lv_obj_set_x( ui_SunRiseData, -229 );
lv_obj_set_y( ui_SunRiseData, -100 );
lv_obj_set_align( ui_SunRiseData, LV_ALIGN_CENTER );
lv_label_set_text(ui_SunRiseData,"88:88");
lv_obj_set_style_text_color(ui_SunRiseData, lv_color_hex(0x7BFB0A), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_SunRiseData, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_SunRiseData, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_SunRiseData, &ui_font_Roboto26, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_SunRiseData, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_SunRiseData, lv_color_hex(0x050000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SunRiseData, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_SunRiseData, lv_color_hex(0xF90505), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_SunRiseData, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_SunRiseData, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_SunRiseData, 6, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_SunRiseData, 6, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_SunRiseData, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_SunRiseData, 6, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SunSetData = lv_label_create(ui_screenInfo);
lv_obj_set_width( ui_SunSetData, 125);
lv_obj_set_height( ui_SunSetData, 44);
lv_obj_set_x( ui_SunSetData, 229 );
lv_obj_set_y( ui_SunSetData, -100 );
lv_obj_set_align( ui_SunSetData, LV_ALIGN_CENTER );
lv_label_set_text(ui_SunSetData,"88:88");
lv_obj_set_style_text_color(ui_SunSetData, lv_color_hex(0x7BFB0A), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_SunSetData, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_SunSetData, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_SunSetData, &ui_font_Roboto26, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_SunSetData, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_SunSetData, lv_color_hex(0x050000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SunSetData, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_SunSetData, lv_color_hex(0xF90505), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_SunSetData, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_SunSetData, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_SunSetData, 6, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_SunSetData, 6, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_SunSetData, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_SunSetData, 6, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_MoonRiseData = lv_label_create(ui_screenInfo);
lv_obj_set_width( ui_MoonRiseData, 125);
lv_obj_set_height( ui_MoonRiseData, 44);
lv_obj_set_x( ui_MoonRiseData, -229 );
lv_obj_set_y( ui_MoonRiseData, -22 );
lv_obj_set_align( ui_MoonRiseData, LV_ALIGN_CENTER );
lv_label_set_text(ui_MoonRiseData,"88:88");
lv_obj_set_style_text_color(ui_MoonRiseData, lv_color_hex(0x7BFB0A), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_MoonRiseData, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_MoonRiseData, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_MoonRiseData, &ui_font_Roboto26, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_MoonRiseData, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_MoonRiseData, lv_color_hex(0x050000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_MoonRiseData, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_MoonRiseData, lv_color_hex(0xF90505), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_MoonRiseData, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_MoonRiseData, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_MoonRiseData, 6, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_MoonRiseData, 6, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_MoonRiseData, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_MoonRiseData, 6, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_MoonSetData = lv_label_create(ui_screenInfo);
lv_obj_set_width( ui_MoonSetData, 125);
lv_obj_set_height( ui_MoonSetData, 44);
lv_obj_set_x( ui_MoonSetData, 229 );
lv_obj_set_y( ui_MoonSetData, -22 );
lv_obj_set_align( ui_MoonSetData, LV_ALIGN_CENTER );
lv_label_set_text(ui_MoonSetData,"88:88");
lv_obj_set_style_text_color(ui_MoonSetData, lv_color_hex(0x7BFB0A), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_MoonSetData, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_MoonSetData, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_MoonSetData, &ui_font_Roboto26, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_MoonSetData, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_MoonSetData, lv_color_hex(0x050000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_MoonSetData, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_MoonSetData, lv_color_hex(0xF90505), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_MoonSetData, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_MoonSetData, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_MoonSetData, 6, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_MoonSetData, 6, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_MoonSetData, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_MoonSetData, 6, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_CountData = lv_label_create(ui_screenInfo);
lv_obj_set_width( ui_CountData, 129);
lv_obj_set_height( ui_CountData, 44);
lv_obj_set_x( ui_CountData, -3 );
lv_obj_set_y( ui_CountData, -177 );
lv_obj_set_align( ui_CountData, LV_ALIGN_CENTER );
lv_label_set_text(ui_CountData,"888,888");
lv_obj_set_style_text_color(ui_CountData, lv_color_hex(0x7BFB0A), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_CountData, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_CountData, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_CountData, &ui_font_Roboto26, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_CountData, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_CountData, lv_color_hex(0x050000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_CountData, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_CountData, lv_color_hex(0xF90505), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_CountData, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_CountData, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_CountData, 6, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_CountData, 6, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_CountData, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_CountData, 6, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Count = lv_label_create(ui_screenInfo);
lv_obj_set_width( ui_Count, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Count, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Count, -7 );
lv_obj_set_y( ui_Count, 3 );
lv_obj_set_align( ui_Count, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_Count,"Count");
lv_obj_set_style_text_color(ui_Count, lv_color_hex(0xD1E1E1), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Count, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Count, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_M000 = lv_img_create(ui_screenInfo);
lv_img_set_src(ui_M000, &ui_img_m000_png);
lv_obj_set_width( ui_M000, LV_SIZE_CONTENT);  /// 100
lv_obj_set_height( ui_M000, LV_SIZE_CONTENT);   /// 100
lv_obj_set_x( ui_M000, -4 );
lv_obj_set_y( ui_M000, -56 );
lv_obj_set_align( ui_M000, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_M000, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_M000, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_M000,500);

ui_M030 = lv_img_create(ui_screenInfo);
lv_img_set_src(ui_M030, &ui_img_m030_png);
lv_obj_set_width( ui_M030, LV_SIZE_CONTENT);  /// 100
lv_obj_set_height( ui_M030, LV_SIZE_CONTENT);   /// 100
lv_obj_set_x( ui_M030, -4 );
lv_obj_set_y( ui_M030, -56 );
lv_obj_set_align( ui_M030, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_M030, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_M030, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_M030,500);

ui_M060 = lv_img_create(ui_screenInfo);
lv_img_set_src(ui_M060, &ui_img_m060_png);
lv_obj_set_width( ui_M060, LV_SIZE_CONTENT);  /// 100
lv_obj_set_height( ui_M060, LV_SIZE_CONTENT);   /// 100
lv_obj_set_x( ui_M060, -4 );
lv_obj_set_y( ui_M060, -56 );
lv_obj_set_align( ui_M060, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_M060, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_M060, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_M060,500);

ui_M090 = lv_img_create(ui_screenInfo);
lv_img_set_src(ui_M090, &ui_img_m090_png);
lv_obj_set_width( ui_M090, LV_SIZE_CONTENT);  /// 100
lv_obj_set_height( ui_M090, LV_SIZE_CONTENT);   /// 100
lv_obj_set_x( ui_M090, -4 );
lv_obj_set_y( ui_M090, -56 );
lv_obj_set_align( ui_M090, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_M090, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_M090, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_M090,500);

ui_M120 = lv_img_create(ui_screenInfo);
lv_img_set_src(ui_M120, &ui_img_m120_png);
lv_obj_set_width( ui_M120, LV_SIZE_CONTENT);  /// 100
lv_obj_set_height( ui_M120, LV_SIZE_CONTENT);   /// 100
lv_obj_set_x( ui_M120, -4 );
lv_obj_set_y( ui_M120, -56 );
lv_obj_set_align( ui_M120, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_M120, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_M120, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_M120,500);

ui_M150 = lv_img_create(ui_screenInfo);
lv_img_set_src(ui_M150, &ui_img_m150_png);
lv_obj_set_width( ui_M150, LV_SIZE_CONTENT);  /// 100
lv_obj_set_height( ui_M150, LV_SIZE_CONTENT);   /// 100
lv_obj_set_x( ui_M150, -4 );
lv_obj_set_y( ui_M150, -56 );
lv_obj_set_align( ui_M150, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_M150, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_M150, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_M150,500);

ui_M180 = lv_img_create(ui_screenInfo);
lv_img_set_src(ui_M180, &ui_img_m180_png);
lv_obj_set_width( ui_M180, LV_SIZE_CONTENT);  /// 100
lv_obj_set_height( ui_M180, LV_SIZE_CONTENT);   /// 100
lv_obj_set_x( ui_M180, -4 );
lv_obj_set_y( ui_M180, -56 );
lv_obj_set_align( ui_M180, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_M180, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_M180, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_M180,500);

ui_M210 = lv_img_create(ui_screenInfo);
lv_img_set_src(ui_M210, &ui_img_m210_png);
lv_obj_set_width( ui_M210, LV_SIZE_CONTENT);  /// 100
lv_obj_set_height( ui_M210, LV_SIZE_CONTENT);   /// 100
lv_obj_set_x( ui_M210, -4 );
lv_obj_set_y( ui_M210, -56 );
lv_obj_set_align( ui_M210, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_M210, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_M210, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_M210,500);

ui_M240 = lv_img_create(ui_screenInfo);
lv_img_set_src(ui_M240, &ui_img_m240_png);
lv_obj_set_width( ui_M240, LV_SIZE_CONTENT);  /// 100
lv_obj_set_height( ui_M240, LV_SIZE_CONTENT);   /// 100
lv_obj_set_x( ui_M240, -4 );
lv_obj_set_y( ui_M240, -56 );
lv_obj_set_align( ui_M240, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_M240, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_M240, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_M240,500);

ui_M270 = lv_img_create(ui_screenInfo);
lv_img_set_src(ui_M270, &ui_img_m270_png);
lv_obj_set_width( ui_M270, LV_SIZE_CONTENT);  /// 100
lv_obj_set_height( ui_M270, LV_SIZE_CONTENT);   /// 100
lv_obj_set_x( ui_M270, -4 );
lv_obj_set_y( ui_M270, -56 );
lv_obj_set_align( ui_M270, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_M270, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_M270, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_M270,500);

ui_M300 = lv_img_create(ui_screenInfo);
lv_img_set_src(ui_M300, &ui_img_m300_png);
lv_obj_set_width( ui_M300, LV_SIZE_CONTENT);  /// -56
lv_obj_set_height( ui_M300, LV_SIZE_CONTENT);   /// 100
lv_obj_set_x( ui_M300, -4 );
lv_obj_set_y( ui_M300, -56 );
lv_obj_set_align( ui_M300, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_M300, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_M300, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_M300,500);

ui_M330 = lv_img_create(ui_screenInfo);
lv_img_set_src(ui_M330, &ui_img_m330_png);
lv_obj_set_width( ui_M330, LV_SIZE_CONTENT);  /// 100
lv_obj_set_height( ui_M330, LV_SIZE_CONTENT);   /// 100
lv_obj_set_x( ui_M330, -4 );
lv_obj_set_y( ui_M330, -56 );
lv_obj_set_align( ui_M330, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_M330, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_M330, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_M330,500);

ui_MoonPhases = lv_label_create(ui_screenInfo);
lv_obj_set_width( ui_MoonPhases, 116);
lv_obj_set_height( ui_MoonPhases, 72);
lv_obj_set_x( ui_MoonPhases, -6 );
lv_obj_set_y( ui_MoonPhases, 72 );
lv_obj_set_align( ui_MoonPhases, LV_ALIGN_CENTER );
lv_label_set_text(ui_MoonPhases,"Moon Phases");
lv_obj_set_style_text_color(ui_MoonPhases, lv_color_hex(0x0B77F6), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_MoonPhases, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_MoonPhases, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_MoonPhases, &ui_font_Roboto28, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_CountData, ui_event_CountData, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_screenInfo, ui_event_screenInfo, LV_EVENT_ALL, NULL);

}
