// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: GSPv45

#include "ui.h"

void ui_screenMain_screen_init(void)
{
ui_screenMain = lv_obj_create(NULL);
lv_obj_clear_flag( ui_screenMain, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_screenMain, lv_color_hex(0x060000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_screenMain, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_pad_left(ui_screenMain, 6, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_screenMain, 6, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_screenMain, 1, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_screenMain, 6, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);

ui_LabelLat = lv_label_create(ui_screenMain);
lv_obj_set_width( ui_LabelLat, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelLat, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelLat, -245 );
lv_obj_set_y( ui_LabelLat, -213 );
lv_obj_set_align( ui_LabelLat, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelLat,"Latitude");
lv_obj_set_style_text_color(ui_LabelLat, lv_color_hex(0xD1E1E1), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelLat, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_LabelLat, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelLat, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelLon = lv_label_create(ui_screenMain);
lv_obj_set_width( ui_LabelLon, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelLon, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelLon, 227 );
lv_obj_set_y( ui_LabelLon, -213 );
lv_obj_set_align( ui_LabelLon, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelLon,"Longitude");
lv_obj_set_style_text_color(ui_LabelLon, lv_color_hex(0xFCF8F8), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelLon, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_LabelLon, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelLon, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelSats = lv_label_create(ui_screenMain);
lv_obj_set_width( ui_LabelSats, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelSats, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelSats, -266 );
lv_obj_set_y( ui_LabelSats, -58 );
lv_obj_set_align( ui_LabelSats, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelSats,"Sats");
lv_obj_set_style_text_color(ui_LabelSats, lv_color_hex(0xD1E1E1), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelSats, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_LabelSats, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelSats, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelDHOP = lv_label_create(ui_screenMain);
lv_obj_set_width( ui_LabelDHOP, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelDHOP, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelDHOP, -251 );
lv_obj_set_y( ui_LabelDHOP, 29 );
lv_obj_set_align( ui_LabelDHOP, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelDHOP,"HDOP");
lv_obj_set_style_text_color(ui_LabelDHOP, lv_color_hex(0xD1E1E1), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelDHOP, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_LabelDHOP, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelDHOP, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LatData = lv_label_create(ui_screenMain);
lv_obj_set_width( ui_LatData, 193);
lv_obj_set_height( ui_LatData, 44);
lv_obj_set_x( ui_LatData, -202 );
lv_obj_set_y( ui_LatData, -178 );
lv_obj_set_align( ui_LatData, LV_ALIGN_CENTER );
lv_label_set_text(ui_LatData,"Acquiring");
lv_obj_set_style_text_color(ui_LatData, lv_color_hex(0x87FC03), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LatData, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_LatData, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LatData, &ui_font_RobotoBold26, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_LatData, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_LatData, lv_color_hex(0x050000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_LatData, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_LatData, lv_color_hex(0xF90505), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_LatData, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_LatData, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_LatData, 6, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_LatData, 6, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_LatData, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_LatData, 6, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LonData = lv_label_create(ui_screenMain);
lv_obj_set_width( ui_LonData, 199);
lv_obj_set_height( ui_LonData, 44);
lv_obj_set_x( ui_LonData, 196 );
lv_obj_set_y( ui_LonData, -177 );
lv_obj_set_align( ui_LonData, LV_ALIGN_CENTER );
lv_label_set_text(ui_LonData,"Satellites");
lv_obj_set_style_text_color(ui_LonData, lv_color_hex(0x87FC03), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LonData, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_LonData, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LonData, &ui_font_RobotoBold26, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_LonData, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_LonData, lv_color_hex(0x050000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_LonData, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_LonData, lv_color_hex(0xF90505), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_LonData, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_LonData, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_LonData, 6, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_LonData, 6, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_LonData, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_LonData, 6, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TimeData = lv_label_create(ui_screenMain);
lv_obj_set_width( ui_TimeData, 125);
lv_obj_set_height( ui_TimeData, 44);
lv_obj_set_x( ui_TimeData, -235 );
lv_obj_set_y( ui_TimeData, -100 );
lv_obj_set_align( ui_TimeData, LV_ALIGN_CENTER );
lv_label_set_text(ui_TimeData,"");
lv_obj_set_style_text_color(ui_TimeData, lv_color_hex(0x87FC03), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_TimeData, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_TimeData, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_TimeData, &ui_font_RobotoBold26, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_TimeData, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_TimeData, lv_color_hex(0x050000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_TimeData, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_TimeData, lv_color_hex(0xF90505), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_TimeData, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_TimeData, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_TimeData, 6, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_TimeData, 6, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_TimeData, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_TimeData, 6, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_DateData = lv_label_create(ui_screenMain);
lv_obj_set_width( ui_DateData, 157);
lv_obj_set_height( ui_DateData, 44);
lv_obj_set_x( ui_DateData, 219 );
lv_obj_set_y( ui_DateData, -100 );
lv_obj_set_align( ui_DateData, LV_ALIGN_CENTER );
lv_label_set_text(ui_DateData,"");
lv_obj_set_style_text_color(ui_DateData, lv_color_hex(0x87FC03), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_DateData, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_DateData, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_DateData, &ui_font_RobotoBold26, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_DateData, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_DateData, lv_color_hex(0x050000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_DateData, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_DateData, lv_color_hex(0xF90505), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_DateData, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_DateData, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_DateData, 6, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_DateData, 6, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_DateData, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_DateData, 6, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_HDOPData = lv_label_create(ui_screenMain);
lv_obj_set_width( ui_HDOPData, 91);
lv_obj_set_height( ui_HDOPData, 44);
lv_obj_set_x( ui_HDOPData, -246 );
lv_obj_set_y( ui_HDOPData, 63 );
lv_obj_set_align( ui_HDOPData, LV_ALIGN_CENTER );
lv_label_set_text(ui_HDOPData,"");
lv_obj_set_style_text_color(ui_HDOPData, lv_color_hex(0x87FC03), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_HDOPData, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_HDOPData, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_HDOPData, &ui_font_RobotoBold26, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_HDOPData, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_HDOPData, lv_color_hex(0x050000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_HDOPData, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_HDOPData, lv_color_hex(0xF90505), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_HDOPData, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_HDOPData, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_HDOPData, 6, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_HDOPData, 6, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_HDOPData, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_HDOPData, 6, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SliderBrightness = lv_slider_create(ui_screenMain);
lv_slider_set_range(ui_SliderBrightness, 0,255);
lv_slider_set_value( ui_SliderBrightness, 0, LV_ANIM_OFF);
if (lv_slider_get_mode(ui_SliderBrightness)==LV_SLIDER_MODE_RANGE ) lv_slider_set_left_value( ui_SliderBrightness, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_SliderBrightness, 420);
lv_obj_set_height( ui_SliderBrightness, 22);
lv_obj_set_x( ui_SliderBrightness, -6 );
lv_obj_set_y( ui_SliderBrightness, 199 );
lv_obj_set_align( ui_SliderBrightness, LV_ALIGN_CENTER );


ui_ImgCompass = lv_img_create(ui_screenMain);
lv_img_set_src(ui_ImgCompass, &ui_img_compass_circle_png);
lv_obj_set_width( ui_ImgCompass, LV_SIZE_CONTENT);  /// 251
lv_obj_set_height( ui_ImgCompass, LV_SIZE_CONTENT);   /// 251
lv_obj_set_x( ui_ImgCompass, -9 );
lv_obj_set_y( ui_ImgCompass, -18 );
lv_obj_set_align( ui_ImgCompass, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ImgCompass, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImgCompass, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_ImgCompass,320);

ui_MikeJoe = lv_label_create(ui_screenMain);
lv_obj_set_width( ui_MikeJoe, 59);
lv_obj_set_height( ui_MikeJoe, 91);
lv_obj_set_x( ui_MikeJoe, -10 );
lv_obj_set_y( ui_MikeJoe, -10 );
lv_obj_set_align( ui_MikeJoe, LV_ALIGN_CENTER );
lv_label_set_text(ui_MikeJoe,"Mike\n\n\nJoe");
lv_obj_set_style_text_color(ui_MikeJoe, lv_color_hex(0xD1E1E1), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_MikeJoe, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_MikeJoe, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_MikeJoe, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_AltData = lv_label_create(ui_screenMain);
lv_obj_set_width( ui_AltData, 134);
lv_obj_set_height( ui_AltData, 45);
lv_obj_set_x( ui_AltData, 231 );
lv_obj_set_y( ui_AltData, -22 );
lv_obj_set_align( ui_AltData, LV_ALIGN_CENTER );
lv_label_set_text(ui_AltData,"");
lv_obj_set_style_text_color(ui_AltData, lv_color_hex(0x87FC03), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_AltData, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_AltData, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_AltData, &ui_font_RobotoBold26, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_AltData, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_AltData, lv_color_hex(0x050000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_AltData, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_AltData, lv_color_hex(0xF90505), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_AltData, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_AltData, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_AltData, 6, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_AltData, 6, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_AltData, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_AltData, 6, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_labelAlt = lv_label_create(ui_screenMain);
lv_obj_set_width( ui_labelAlt, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_labelAlt, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_labelAlt, 250 );
lv_obj_set_y( ui_labelAlt, -58 );
lv_obj_set_align( ui_labelAlt, LV_ALIGN_CENTER );
lv_label_set_text(ui_labelAlt,"Alitude");
lv_obj_set_style_text_color(ui_labelAlt, lv_color_hex(0xD1E1E1), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_labelAlt, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_labelAlt, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_labelAlt, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelSpeed = lv_label_create(ui_screenMain);
lv_obj_set_width( ui_LabelSpeed, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelSpeed, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelSpeed, 258 );
lv_obj_set_y( ui_LabelSpeed, 29 );
lv_obj_set_align( ui_LabelSpeed, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelSpeed,"Speed");
lv_obj_set_style_text_color(ui_LabelSpeed, lv_color_hex(0xD1E1E1), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelSpeed, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_LabelSpeed, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelSpeed, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SpeedData = lv_label_create(ui_screenMain);
lv_obj_set_width( ui_SpeedData, 134);
lv_obj_set_height( ui_SpeedData, 44);
lv_obj_set_x( ui_SpeedData, 231 );
lv_obj_set_y( ui_SpeedData, 63 );
lv_obj_set_align( ui_SpeedData, LV_ALIGN_CENTER );
lv_label_set_text(ui_SpeedData,"");
lv_obj_set_style_text_color(ui_SpeedData, lv_color_hex(0x87FC03), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_SpeedData, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_SpeedData, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_SpeedData, &ui_font_RobotoBold26, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_SpeedData, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_SpeedData, lv_color_hex(0x050000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SpeedData, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_SpeedData, lv_color_hex(0xF90505), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_SpeedData, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_SpeedData, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_SpeedData, 6, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_SpeedData, 6, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_SpeedData, 6, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_SpeedData, 6, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_labelDist = lv_label_create(ui_screenMain);
lv_obj_set_width( ui_labelDist, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_labelDist, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_labelDist, 244 );
lv_obj_set_y( ui_labelDist, 109 );
lv_obj_set_align( ui_labelDist, LV_ALIGN_CENTER );
lv_label_set_text(ui_labelDist,"Distance");
lv_obj_set_style_text_color(ui_labelDist, lv_color_hex(0xD1E1E1), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_labelDist, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_labelDist, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_labelDist, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_DistData = lv_label_create(ui_screenMain);
lv_obj_set_width( ui_DistData, 144);
lv_obj_set_height( ui_DistData, 44);
lv_obj_set_x( ui_DistData, 226 );
lv_obj_set_y( ui_DistData, 143 );
lv_obj_set_align( ui_DistData, LV_ALIGN_CENTER );
lv_label_set_text(ui_DistData,"");
lv_obj_set_style_text_color(ui_DistData, lv_color_hex(0x87FC03), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_DistData, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_DistData, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_DistData, &ui_font_RobotoBold26, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_DistData, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_DistData, lv_color_hex(0x050000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_DistData, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_DistData, lv_color_hex(0xF90505), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_DistData, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_DistData, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_DistData, 6, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_DistData, 6, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_DistData, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_DistData, 6, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SatData = lv_label_create(ui_screenMain);
lv_obj_set_width( ui_SatData, 84);
lv_obj_set_height( ui_SatData, 44);
lv_obj_set_x( ui_SatData, -248 );
lv_obj_set_y( ui_SatData, -22 );
lv_obj_set_align( ui_SatData, LV_ALIGN_CENTER );
lv_label_set_text(ui_SatData,"");
lv_obj_set_style_text_color(ui_SatData, lv_color_hex(0x87FC03), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_SatData, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_SatData, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_SatData, &ui_font_RobotoBold26, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_SatData, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_SatData, lv_color_hex(0x050000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SatData, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_SatData, lv_color_hex(0xF90505), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_SatData, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_SatData, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_SatData, 6, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_SatData, 6, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_SatData, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_SatData, 6, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_HeadingData = lv_label_create(ui_screenMain);
lv_obj_set_width( ui_HeadingData, 98);
lv_obj_set_height( ui_HeadingData, 45);
lv_obj_set_x( ui_HeadingData, -9 );
lv_obj_set_y( ui_HeadingData, -14 );
lv_obj_set_align( ui_HeadingData, LV_ALIGN_CENTER );
lv_label_set_long_mode(ui_HeadingData,LV_LABEL_LONG_SCROLL_CIRCULAR);
lv_label_set_text(ui_HeadingData,"Acquring Satellites");
lv_obj_set_style_text_color(ui_HeadingData, lv_color_hex(0x87FC03), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_HeadingData, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_HeadingData, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_HeadingData, &ui_font_RobotoBold26, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_HeadingData, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_HeadingData, lv_color_hex(0x050000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_HeadingData, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_HeadingData, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_HeadingData, 6, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_HeadingData, 6, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_HeadingData, 6, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_HeadingData, 6, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_HeadingData, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_SCROLLED );
lv_obj_set_style_text_opa(ui_HeadingData, 255, LV_PART_MAIN| LV_STATE_SCROLLED);
lv_obj_set_style_text_align(ui_HeadingData, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_SCROLLED);
lv_obj_set_style_text_font(ui_HeadingData, &ui_font_RobotoBold26, LV_PART_MAIN| LV_STATE_SCROLLED);

ui_BtnAlt = lv_btn_create(ui_screenMain);
lv_obj_set_width( ui_BtnAlt, 133);
lv_obj_set_height( ui_BtnAlt, 44);
lv_obj_set_x( ui_BtnAlt, 230 );
lv_obj_set_y( ui_BtnAlt, -22 );
lv_obj_set_align( ui_BtnAlt, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_BtnAlt, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_BtnAlt, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_opa(ui_BtnAlt, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BtnSpeed = lv_btn_create(ui_screenMain);
lv_obj_set_width( ui_BtnSpeed, 136);
lv_obj_set_height( ui_BtnSpeed, 44);
lv_obj_set_x( ui_BtnSpeed, 229 );
lv_obj_set_y( ui_BtnSpeed, 63 );
lv_obj_set_align( ui_BtnSpeed, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_BtnSpeed, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_BtnSpeed, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_opa(ui_BtnSpeed, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BtnDist = lv_btn_create(ui_screenMain);
lv_obj_set_width( ui_BtnDist, 141);
lv_obj_set_height( ui_BtnDist, 44);
lv_obj_set_x( ui_BtnDist, 224 );
lv_obj_set_y( ui_BtnDist, 143 );
lv_obj_set_align( ui_BtnDist, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_BtnDist, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_BtnDist, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_opa(ui_BtnDist, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BtnDate = lv_btn_create(ui_screenMain);
lv_obj_set_width( ui_BtnDate, 154);
lv_obj_set_height( ui_BtnDate, 44);
lv_obj_set_x( ui_BtnDate, 218 );
lv_obj_set_y( ui_BtnDate, -100 );
lv_obj_set_align( ui_BtnDate, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_BtnDate, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_BtnDate, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_opa(ui_BtnDate, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BtnTime = lv_btn_create(ui_screenMain);
lv_obj_set_width( ui_BtnTime, 124);
lv_obj_set_height( ui_BtnTime, 44);
lv_obj_set_x( ui_BtnTime, -234 );
lv_obj_set_y( ui_BtnTime, -100 );
lv_obj_set_align( ui_BtnTime, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_BtnTime, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_BtnTime, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_opa(ui_BtnTime, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BtnLat = lv_btn_create(ui_screenMain);
lv_obj_set_width( ui_BtnLat, 190);
lv_obj_set_height( ui_BtnLat, 45);
lv_obj_set_x( ui_BtnLat, -201 );
lv_obj_set_y( ui_BtnLat, -177 );
lv_obj_set_align( ui_BtnLat, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_BtnLat, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_BtnLat, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_opa(ui_BtnLat, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BtnLon = lv_btn_create(ui_screenMain);
lv_obj_set_width( ui_BtnLon, 198);
lv_obj_set_height( ui_BtnLon, 42);
lv_obj_set_x( ui_BtnLon, 198 );
lv_obj_set_y( ui_BtnLon, -176 );
lv_obj_set_align( ui_BtnLon, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_BtnLon, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_BtnLon, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_opa(ui_BtnLon, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_BtnLon, 6, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_BtnLon, 6, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_BtnLon, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_BtnLon, 6, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Volts = lv_label_create(ui_screenMain);
lv_obj_set_width( ui_Volts, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Volts, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Volts, -247 );
lv_obj_set_y( ui_Volts, 109 );
lv_obj_set_align( ui_Volts, LV_ALIGN_CENTER );
lv_label_set_text(ui_Volts,"Voltage");
lv_obj_set_style_text_color(ui_Volts, lv_color_hex(0xD1E1E1), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Volts, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Volts, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Volts, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelVolts = lv_label_create(ui_screenMain);
lv_obj_set_width( ui_LabelVolts, 123);
lv_obj_set_height( ui_LabelVolts, 44);
lv_obj_set_x( ui_LabelVolts, -233 );
lv_obj_set_y( ui_LabelVolts, 143 );
lv_obj_set_align( ui_LabelVolts, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelVolts,"");
lv_obj_set_style_text_color(ui_LabelVolts, lv_color_hex(0x87FC03), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelVolts, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_LabelVolts, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelVolts, &ui_font_RobotoBold26, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_LabelVolts, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_LabelVolts, lv_color_hex(0x050000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_LabelVolts, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_LabelVolts, lv_color_hex(0xF90505), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_LabelVolts, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_LabelVolts, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_LabelVolts, 6, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_LabelVolts, 6, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_LabelVolts, 6, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_LabelVolts, 6, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelBatteryLevel = lv_label_create(ui_screenMain);
lv_obj_set_width( ui_LabelBatteryLevel, 87);
lv_obj_set_height( ui_LabelBatteryLevel, 31);
lv_obj_set_x( ui_LabelBatteryLevel, 12 );
lv_obj_set_y( ui_LabelBatteryLevel, 354 );
lv_label_set_text(ui_LabelBatteryLevel,"");
lv_obj_set_style_text_color(ui_LabelBatteryLevel, lv_color_hex(0x87FC03), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelBatteryLevel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_LabelBatteryLevel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelBatteryLevel, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_LabelBatteryLevel, lv_color_hex(0x000003), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_LabelBatteryLevel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Flash = lv_img_create(ui_screenMain);
lv_img_set_src(ui_Flash, &ui_img_flash_png);
lv_obj_set_width( ui_Flash, LV_SIZE_CONTENT);  /// 13
lv_obj_set_height( ui_Flash, LV_SIZE_CONTENT);   /// 18
lv_obj_set_x( ui_Flash, -189 );
lv_obj_set_y( ui_Flash, 144 );
lv_obj_set_align( ui_Flash, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Flash, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Flash, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_opa(ui_Flash, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lblDate = lv_label_create(ui_screenMain);
lv_obj_set_width( ui_lblDate, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lblDate, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lblDate, 262 );
lv_obj_set_y( ui_lblDate, -138 );
lv_obj_set_align( ui_lblDate, LV_ALIGN_CENTER );
lv_label_set_text(ui_lblDate,"Date");
lv_obj_set_style_text_color(ui_lblDate, lv_color_hex(0xD1E1E1), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_lblDate, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_lblDate, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label6 = lv_label_create(ui_screenMain);
lv_obj_set_width( ui_Label6, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label6, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label6, -266 );
lv_obj_set_y( ui_Label6, -138 );
lv_obj_set_align( ui_Label6, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label6,"Time");
lv_obj_set_style_text_color(ui_Label6, lv_color_hex(0xD1E1E1), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label6, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label6, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_SliderBrightness, ui_event_SliderBrightness, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_BtnAlt, ui_event_BtnAlt, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_BtnSpeed, ui_event_BtnSpeed, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_BtnDist, ui_event_BtnDist, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_BtnDate, ui_event_BtnDate, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_BtnTime, ui_event_BtnTime, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_BtnLat, ui_event_BtnLat, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_BtnLon, ui_event_BtnLon, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_LabelBatteryLevel, ui_event_LabelBatteryLevel, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_screenMain, ui_event_screenMain, LV_EVENT_ALL, NULL);

}
