// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: GSPv45

#include "ui.h"

void ui_screenSats_screen_init(void)
{
ui_screenSats = lv_obj_create(NULL);
lv_obj_clear_flag( ui_screenSats, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_screenSats, lv_color_hex(0x020202), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_screenSats, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SatsCircle = lv_img_create(ui_screenSats);
lv_img_set_src(ui_SatsCircle, &ui_img_satview_png);
lv_obj_set_width( ui_SatsCircle, LV_SIZE_CONTENT);  /// 450
lv_obj_set_height( ui_SatsCircle, LV_SIZE_CONTENT);   /// 440
lv_obj_set_x( ui_SatsCircle, 0 );
lv_obj_set_y( ui_SatsCircle, -4 );
lv_obj_set_align( ui_SatsCircle, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_SatsCircle, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_SatsCircle, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_SatsCircle,305);

ui_Sat00 = lv_label_create(ui_screenSats);
lv_obj_set_width( ui_Sat00, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Sat00, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Sat00, 6 );
lv_obj_set_y( ui_Sat00, -95 );
lv_obj_set_align( ui_Sat00, LV_ALIGN_CENTER );
lv_label_set_text(ui_Sat00,"00");
lv_obj_set_style_text_color(ui_Sat00, lv_color_hex(0x0AF805), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Sat00, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Sat00, &ui_font_Roboto28, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Sat01 = lv_label_create(ui_screenSats);
lv_obj_set_width( ui_Sat01, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Sat01, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Sat01, 81 );
lv_obj_set_y( ui_Sat01, -60 );
lv_obj_set_align( ui_Sat01, LV_ALIGN_CENTER );
lv_label_set_text(ui_Sat01,"01");
lv_obj_set_style_text_color(ui_Sat01, lv_color_hex(0x0AF805), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Sat01, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Sat01, &ui_font_Roboto28, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Sat02 = lv_label_create(ui_screenSats);
lv_obj_set_width( ui_Sat02, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Sat02, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Sat02, 150 );
lv_obj_set_y( ui_Sat02, 16 );
lv_obj_set_align( ui_Sat02, LV_ALIGN_CENTER );
lv_label_set_text(ui_Sat02,"02");
lv_obj_set_style_text_color(ui_Sat02, lv_color_hex(0x0AF805), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Sat02, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Sat02, &ui_font_Roboto28, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Sat03 = lv_label_create(ui_screenSats);
lv_obj_set_width( ui_Sat03, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Sat03, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Sat03, 95 );
lv_obj_set_y( ui_Sat03, -6 );
lv_obj_set_align( ui_Sat03, LV_ALIGN_CENTER );
lv_label_set_text(ui_Sat03,"03");
lv_obj_set_style_text_color(ui_Sat03, lv_color_hex(0x0AF805), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Sat03, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Sat03, &ui_font_Roboto28, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Sat04 = lv_label_create(ui_screenSats);
lv_obj_set_width( ui_Sat04, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Sat04, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Sat04, 89 );
lv_obj_set_y( ui_Sat04, 48 );
lv_obj_set_align( ui_Sat04, LV_ALIGN_CENTER );
lv_label_set_text(ui_Sat04,"04");
lv_obj_set_style_text_color(ui_Sat04, lv_color_hex(0x0AF805), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Sat04, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Sat04, &ui_font_Roboto28, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Sat05 = lv_label_create(ui_screenSats);
lv_obj_set_width( ui_Sat05, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Sat05, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Sat05, 64 );
lv_obj_set_y( ui_Sat05, 87 );
lv_obj_set_align( ui_Sat05, LV_ALIGN_CENTER );
lv_label_set_text(ui_Sat05,"05");
lv_obj_set_style_text_color(ui_Sat05, lv_color_hex(0x0AF805), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Sat05, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Sat05, &ui_font_Roboto28, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Sat06 = lv_label_create(ui_screenSats);
lv_obj_set_width( ui_Sat06, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Sat06, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Sat06, -2 );
lv_obj_set_y( ui_Sat06, 73 );
lv_obj_set_align( ui_Sat06, LV_ALIGN_CENTER );
lv_label_set_text(ui_Sat06,"06");
lv_obj_set_style_text_color(ui_Sat06, lv_color_hex(0x0AF805), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Sat06, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Sat06, &ui_font_Roboto28, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Sat07 = lv_label_create(ui_screenSats);
lv_obj_set_width( ui_Sat07, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Sat07, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Sat07, -38 );
lv_obj_set_y( ui_Sat07, 58 );
lv_obj_set_align( ui_Sat07, LV_ALIGN_CENTER );
lv_label_set_text(ui_Sat07,"07");
lv_obj_set_style_text_color(ui_Sat07, lv_color_hex(0x0AF805), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Sat07, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Sat07, &ui_font_Roboto28, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Sat08 = lv_label_create(ui_screenSats);
lv_obj_set_width( ui_Sat08, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Sat08, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Sat08, -59 );
lv_obj_set_y( ui_Sat08, 29 );
lv_obj_set_align( ui_Sat08, LV_ALIGN_CENTER );
lv_label_set_text(ui_Sat08,"08");
lv_obj_set_style_text_color(ui_Sat08, lv_color_hex(0x0AF805), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Sat08, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Sat08, &ui_font_Roboto28, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Sat09 = lv_label_create(ui_screenSats);
lv_obj_set_width( ui_Sat09, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Sat09, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Sat09, -74 );
lv_obj_set_y( ui_Sat09, -5 );
lv_obj_set_align( ui_Sat09, LV_ALIGN_CENTER );
lv_label_set_text(ui_Sat09,"09");
lv_obj_set_style_text_color(ui_Sat09, lv_color_hex(0x0AF805), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Sat09, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Sat09, &ui_font_Roboto28, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Sat10 = lv_label_create(ui_screenSats);
lv_obj_set_width( ui_Sat10, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Sat10, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Sat10, -62 );
lv_obj_set_y( ui_Sat10, -39 );
lv_obj_set_align( ui_Sat10, LV_ALIGN_CENTER );
lv_label_set_text(ui_Sat10,"10");
lv_obj_set_style_text_color(ui_Sat10, lv_color_hex(0x0AF805), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Sat10, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Sat10, &ui_font_Roboto28, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Sat11 = lv_label_create(ui_screenSats);
lv_obj_set_width( ui_Sat11, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Sat11, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Sat11, -53 );
lv_obj_set_y( ui_Sat11, 108 );
lv_obj_set_align( ui_Sat11, LV_ALIGN_CENTER );
lv_label_set_text(ui_Sat11,"11");
lv_obj_set_style_text_color(ui_Sat11, lv_color_hex(0x0AF805), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Sat11, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Sat11, &ui_font_Roboto28, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Sat12 = lv_label_create(ui_screenSats);
lv_obj_set_width( ui_Sat12, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Sat12, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Sat12, -112 );
lv_obj_set_y( ui_Sat12, 128 );
lv_obj_set_align( ui_Sat12, LV_ALIGN_CENTER );
lv_label_set_text(ui_Sat12,"12");
lv_obj_set_style_text_color(ui_Sat12, lv_color_hex(0x0AF805), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Sat12, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Sat12, &ui_font_Roboto28, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Sat13 = lv_label_create(ui_screenSats);
lv_obj_set_width( ui_Sat13, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Sat13, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Sat13, -78 );
lv_obj_set_y( ui_Sat13, 86 );
lv_obj_set_align( ui_Sat13, LV_ALIGN_CENTER );
lv_label_set_text(ui_Sat13,"13");
lv_obj_set_style_text_color(ui_Sat13, lv_color_hex(0x0AF805), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Sat13, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Sat13, &ui_font_Roboto28, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Sat14 = lv_label_create(ui_screenSats);
lv_obj_set_width( ui_Sat14, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Sat14, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Sat14, -130 );
lv_obj_set_y( ui_Sat14, 87 );
lv_obj_set_align( ui_Sat14, LV_ALIGN_CENTER );
lv_label_set_text(ui_Sat14,"14");
lv_obj_set_style_text_color(ui_Sat14, lv_color_hex(0x0AF805), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Sat14, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Sat14, &ui_font_Roboto28, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Sat15 = lv_label_create(ui_screenSats);
lv_obj_set_width( ui_Sat15, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Sat15, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Sat15, -147 );
lv_obj_set_y( ui_Sat15, 55 );
lv_obj_set_align( ui_Sat15, LV_ALIGN_CENTER );
lv_label_set_text(ui_Sat15,"15");
lv_obj_set_style_text_color(ui_Sat15, lv_color_hex(0x0AF805), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Sat15, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Sat15, &ui_font_Roboto28, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Sat16 = lv_label_create(ui_screenSats);
lv_obj_set_width( ui_Sat16, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Sat16, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Sat16, -98 );
lv_obj_set_y( ui_Sat16, 52 );
lv_obj_set_align( ui_Sat16, LV_ALIGN_CENTER );
lv_label_set_text(ui_Sat16,"16");
lv_obj_set_style_text_color(ui_Sat16, lv_color_hex(0x0AF805), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Sat16, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Sat16, &ui_font_Roboto28, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Sat17 = lv_label_create(ui_screenSats);
lv_obj_set_width( ui_Sat17, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Sat17, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Sat17, -151 );
lv_obj_set_y( ui_Sat17, 24 );
lv_obj_set_align( ui_Sat17, LV_ALIGN_CENTER );
lv_label_set_text(ui_Sat17,"17");
lv_obj_set_style_text_color(ui_Sat17, lv_color_hex(0x0AF805), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Sat17, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Sat17, &ui_font_Roboto28, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Sat18 = lv_label_create(ui_screenSats);
lv_obj_set_width( ui_Sat18, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Sat18, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Sat18, -115 );
lv_obj_set_y( ui_Sat18, 22 );
lv_obj_set_align( ui_Sat18, LV_ALIGN_CENTER );
lv_label_set_text(ui_Sat18,"18");
lv_obj_set_style_text_color(ui_Sat18, lv_color_hex(0x0AF805), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Sat18, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Sat18, &ui_font_Roboto28, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Sat19 = lv_label_create(ui_screenSats);
lv_obj_set_width( ui_Sat19, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Sat19, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Sat19, -167 );
lv_obj_set_y( ui_Sat19, -9 );
lv_obj_set_align( ui_Sat19, LV_ALIGN_CENTER );
lv_label_set_text(ui_Sat19,"19");
lv_obj_set_style_text_color(ui_Sat19, lv_color_hex(0x0AF805), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Sat19, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Sat19, &ui_font_Roboto28, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Sat20 = lv_label_create(ui_screenSats);
lv_obj_set_width( ui_Sat20, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Sat20, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Sat20, -121 );
lv_obj_set_y( ui_Sat20, -12 );
lv_obj_set_align( ui_Sat20, LV_ALIGN_CENTER );
lv_label_set_text(ui_Sat20,"20");
lv_obj_set_style_text_color(ui_Sat20, lv_color_hex(0x0AF805), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Sat20, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Sat20, &ui_font_Roboto28, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Sat21 = lv_label_create(ui_screenSats);
lv_obj_set_width( ui_Sat21, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Sat21, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Sat21, -157 );
lv_obj_set_y( ui_Sat21, -43 );
lv_obj_set_align( ui_Sat21, LV_ALIGN_CENTER );
lv_label_set_text(ui_Sat21,"21");
lv_obj_set_style_text_color(ui_Sat21, lv_color_hex(0x0AF805), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Sat21, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Sat21, &ui_font_Roboto28, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Sat22 = lv_label_create(ui_screenSats);
lv_obj_set_width( ui_Sat22, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Sat22, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Sat22, -152 );
lv_obj_set_y( ui_Sat22, -70 );
lv_obj_set_align( ui_Sat22, LV_ALIGN_CENTER );
lv_label_set_text(ui_Sat22,"22");
lv_obj_set_style_text_color(ui_Sat22, lv_color_hex(0x0AF805), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Sat22, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Sat22, &ui_font_Roboto28, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Sat23 = lv_label_create(ui_screenSats);
lv_obj_set_width( ui_Sat23, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Sat23, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Sat23, -111 );
lv_obj_set_y( ui_Sat23, -49 );
lv_obj_set_align( ui_Sat23, LV_ALIGN_CENTER );
lv_label_set_text(ui_Sat23,"23");
lv_obj_set_style_text_color(ui_Sat23, lv_color_hex(0x0AF805), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Sat23, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Sat23, &ui_font_Roboto28, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Sat24 = lv_label_create(ui_screenSats);
lv_obj_set_width( ui_Sat24, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Sat24, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Sat24, 186 );
lv_obj_set_y( ui_Sat24, -29 );
lv_obj_set_align( ui_Sat24, LV_ALIGN_CENTER );
lv_label_set_text(ui_Sat24,"24");
lv_obj_set_style_text_color(ui_Sat24, lv_color_hex(0x0AF805), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Sat24, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Sat24, &ui_font_Roboto28, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Sat25 = lv_label_create(ui_screenSats);
lv_obj_set_width( ui_Sat25, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Sat25, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Sat25, -115 );
lv_obj_set_y( ui_Sat25, -79 );
lv_obj_set_align( ui_Sat25, LV_ALIGN_CENTER );
lv_label_set_text(ui_Sat25,"25");
lv_obj_set_style_text_color(ui_Sat25, lv_color_hex(0x0AF805), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Sat25, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Sat25, &ui_font_Roboto28, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Sat26 = lv_label_create(ui_screenSats);
lv_obj_set_width( ui_Sat26, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Sat26, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Sat26, 181 );
lv_obj_set_y( ui_Sat26, -65 );
lv_obj_set_align( ui_Sat26, LV_ALIGN_CENTER );
lv_label_set_text(ui_Sat26,"26");
lv_obj_set_style_text_color(ui_Sat26, lv_color_hex(0x0AF805), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Sat26, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Sat26, &ui_font_Roboto28, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Sat27 = lv_label_create(ui_screenSats);
lv_obj_set_width( ui_Sat27, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Sat27, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Sat27, -121 );
lv_obj_set_y( ui_Sat27, -124 );
lv_obj_set_align( ui_Sat27, LV_ALIGN_CENTER );
lv_label_set_text(ui_Sat27,"27");
lv_obj_set_style_text_color(ui_Sat27, lv_color_hex(0x0AF805), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Sat27, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Sat27, &ui_font_Roboto28, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Sat28 = lv_label_create(ui_screenSats);
lv_obj_set_width( ui_Sat28, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Sat28, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Sat28, 160 );
lv_obj_set_y( ui_Sat28, -89 );
lv_obj_set_align( ui_Sat28, LV_ALIGN_CENTER );
lv_label_set_text(ui_Sat28,"28");
lv_obj_set_style_text_color(ui_Sat28, lv_color_hex(0x0AF805), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Sat28, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Sat28, &ui_font_Roboto28, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Sat29 = lv_label_create(ui_screenSats);
lv_obj_set_width( ui_Sat29, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Sat29, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Sat29, -85 );
lv_obj_set_y( ui_Sat29, -132 );
lv_obj_set_align( ui_Sat29, LV_ALIGN_CENTER );
lv_label_set_text(ui_Sat29,"29");
lv_obj_set_style_text_color(ui_Sat29, lv_color_hex(0x0AF805), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Sat29, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Sat29, &ui_font_Roboto28, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Sat30 = lv_label_create(ui_screenSats);
lv_obj_set_width( ui_Sat30, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Sat30, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Sat30, 138 );
lv_obj_set_y( ui_Sat30, -117 );
lv_obj_set_align( ui_Sat30, LV_ALIGN_CENTER );
lv_label_set_text(ui_Sat30,"30");
lv_obj_set_style_text_color(ui_Sat30, lv_color_hex(0x0AF805), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Sat30, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Sat30, &ui_font_Roboto28, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Sat31 = lv_label_create(ui_screenSats);
lv_obj_set_width( ui_Sat31, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Sat31, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Sat31, -29 );
lv_obj_set_y( ui_Sat31, -160 );
lv_obj_set_align( ui_Sat31, LV_ALIGN_CENTER );
lv_label_set_text(ui_Sat31,"31");
lv_obj_set_style_text_color(ui_Sat31, lv_color_hex(0x0AF805), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Sat31, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Sat31, &ui_font_Roboto28, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Sat32 = lv_label_create(ui_screenSats);
lv_obj_set_width( ui_Sat32, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Sat32, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Sat32, 107 );
lv_obj_set_y( ui_Sat32, -146 );
lv_obj_set_align( ui_Sat32, LV_ALIGN_CENTER );
lv_label_set_text(ui_Sat32,"32");
lv_obj_set_style_text_color(ui_Sat32, lv_color_hex(0x0AF805), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Sat32, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Sat32, &ui_font_Roboto28, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_screenSats, ui_event_screenSats, LV_EVENT_ALL, NULL);

}
