// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: GSP_2.18

#include "ui.h"

void ui_scrSplash_screen_init(void)
{
    ui_scrSplash = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_scrSplash, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image1 = lv_img_create(ui_scrSplash);
    lv_img_set_src(ui_Image1, &ui_img_splash_screen_2_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 586
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 439
    lv_obj_set_x(ui_Image1, -2);
    lv_obj_set_y(ui_Image1, -12);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_txtTitle = lv_label_create(ui_scrSplash);
    lv_obj_set_width(ui_txtTitle, 375);
    lv_obj_set_height(ui_txtTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_txtTitle, 29);
    lv_obj_set_y(ui_txtTitle, -122);
    lv_obj_set_align(ui_txtTitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_txtTitle, "Title");
    lv_obj_set_style_text_color(ui_txtTitle, lv_color_hex(0x330AE3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_txtTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_txtTitle, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_txtTitle, &ui_font_RobotoBold32, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_txtTitle, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_txtTitle, lv_color_hex(0x058EE5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_txtTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_txtTitle, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_txtTitle, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_txtTitle, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_txtTitle, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_txtVersion = lv_label_create(ui_scrSplash);
    lv_obj_set_width(ui_txtVersion, 375);
    lv_obj_set_height(ui_txtVersion, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_txtVersion, 29);
    lv_obj_set_y(ui_txtVersion, -62);
    lv_obj_set_align(ui_txtVersion, LV_ALIGN_CENTER);
    lv_label_set_text(ui_txtVersion, "Version");
    lv_obj_set_style_text_color(ui_txtVersion, lv_color_hex(0x000702), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_txtVersion, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_txtVersion, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_txtVersion, &ui_font_RobotoBold32, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_txtVersion, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_txtVersion, lv_color_hex(0x06FE3F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_txtVersion, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_txtVersion, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_txtVersion, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_txtVersion, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_txtVersion, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_txtStatus1 = lv_label_create(ui_scrSplash);
    lv_obj_set_width(ui_txtStatus1, 375);
    lv_obj_set_height(ui_txtStatus1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_txtStatus1, 29);
    lv_obj_set_y(ui_txtStatus1, 58);
    lv_obj_set_align(ui_txtStatus1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_txtStatus1, "Status1");
    lv_obj_set_style_text_color(ui_txtStatus1, lv_color_hex(0x0EF53A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_txtStatus1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_txtStatus1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_txtStatus1, &ui_font_RobotoBold32, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_txtStatus1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_txtStatus1, lv_color_hex(0x3406F4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_txtStatus1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_txtStatus1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_txtStatus1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_txtStatus1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_txtStatus1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_txtStatus2 = lv_label_create(ui_scrSplash);
    lv_obj_set_width(ui_txtStatus2, 375);
    lv_obj_set_height(ui_txtStatus2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_txtStatus2, 29);
    lv_obj_set_y(ui_txtStatus2, 118);
    lv_obj_set_align(ui_txtStatus2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_txtStatus2, "Status2");
    lv_obj_set_style_text_color(ui_txtStatus2, lv_color_hex(0x0EF53A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_txtStatus2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_txtStatus2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_txtStatus2, &ui_font_RobotoBold32, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_txtStatus2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_txtStatus2, lv_color_hex(0xF91908), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_txtStatus2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_txtStatus2, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_txtStatus2, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_txtStatus2, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_txtStatus2, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_txtStatus3 = lv_label_create(ui_scrSplash);
    lv_obj_set_width(ui_txtStatus3, 375);
    lv_obj_set_height(ui_txtStatus3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_txtStatus3, 29);
    lv_obj_set_y(ui_txtStatus3, -2);
    lv_obj_set_align(ui_txtStatus3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_txtStatus3, "SquareLine Version 1.5.0");
    lv_obj_set_style_text_color(ui_txtStatus3, lv_color_hex(0xF9B90C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_txtStatus3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_txtStatus3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_txtStatus3, &ui_font_RobotoBold32, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_txtStatus3, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_txtStatus3, lv_color_hex(0x0A0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_txtStatus3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_txtStatus3, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_txtStatus3, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_txtStatus3, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_txtStatus3, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Bar1 = lv_bar_create(ui_scrSplash);
    lv_bar_set_value(ui_Bar1, 100, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Bar1, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Bar1, 17);
    lv_obj_set_height(ui_Bar1, 292);
    lv_obj_set_x(ui_Bar1, 233);
    lv_obj_set_y(ui_Bar1, -2);
    lv_obj_set_align(ui_Bar1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Bar1, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_bg_color(ui_Bar1, lv_color_hex(0xF407F7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Bar1, lv_color_hex(0x80020E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Bar1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Bar1, 300, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Bar1, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Bar1, lv_color_hex(0x2D7DF2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Bar1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Bar1, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Bar1, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Bar1, lv_color_hex(0xCFF111), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);


}
